# Generated by Django 2.2.7 on 2019-12-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('i_frame', models.BooleanField(default=False, verbose_name='是否为外链')),
                ('name', models.CharField(max_length=255, verbose_name='菜单名称')),
                ('component', models.CharField(blank=True, max_length=255, verbose_name='组件')),
                ('pid', models.IntegerField(blank=True, verbose_name='上级菜单ID')),
                ('sort', models.IntegerField(blank=True, verbose_name='排序')),
                ('icon', models.CharField(blank=True, max_length=255, verbose_name='图标')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='链接地址')),
                ('cache', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('component_name', models.CharField(blank=True, default='-', max_length=255, verbose_name='组件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.CharField(blank=True, max_length=255, verbose_name='权限')),
                ('type', models.IntegerField(blank=True, verbose_name='菜单类型')),
            ],
            options={
                'verbose_name': '菜单信息',
                'verbose_name_plural': '菜单信息',
                'db_table': 'menu',
            },
        ),
    ]
