# Generated by Django 2.2.7 on 2019-12-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('level', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ManyToManyField(related_name='menu', to='menu.Menu')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
            },
        ),
    ]
